---
Name: productcomparison
After: 'shop/*'
---
Product:
  extensions:
    - 'ProductFeaturesExtension'
Product_Controller:
  extensions:
    - 'ProductControllerFeaturesExtension'
ProductCatalogAdmin:
  managed_models:
    - 'Product'
    - 'ProductCategory'
    - 'Feature'
    - 'FeatureGroup'

LeftAndMain:
  extra_requirements_javascript:
    - shop_comparison/javascript/shop_comparsion_admin.js